import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from "react";

import Card, {CardType, Suit, Rank} from '@/components/Card'

function EventSourceCard() {
    const [cards, setCards] = useState<CardType[]>([])

    useEffect(() => {
        const eventSource = new EventSource('http://localhost:8080/sse');

        eventSource.onmessage = (event) => {
            const newData = JSON.parse(event.data);
            setCards(newData);
        }
        eventSource.onerror = (error) => {
            console.error("SSE error:", error);
        }

        return () => {
            eventSource.close();
        }
    }, [cards]);

    if (!cards) { return <div>Loading...</div> }

    const c1: CardType = {
        suit: cards[0].suit as Suit,
        rank: cards[0].rank as Rank
    }
    const c2: CardType = {
        suit: cards[1].suit as Suit,
        rank: cards[1].rank as Rank
    }

    if ((!c1.suit) || (!c1.rank) || (!c2.suit) || (!c2.rank)) {
        return <div>Missing card data</div>
    }

    return (
        <div className={"flex"}>
            <Card suit={c1.suit} rank={c1.rank} />
            <Card suit={c2.suit} rank={c2.rank} />
        </div>
    )
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Poker logger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline pb-10">
          Your hands is ...
        </h1>
        <EventSourceCard />
      </main>
    </>
  )
}
