name: Test
on:
  push:
    branches:
      - "**"
  pull_request: {}

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install libnfc6 libnfc-dev -y
      - name: Lint
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...
      - name: go vet
        run: |
          go vet ./...
      - name: Build
        run: |
          go build -o app ./cmd/cmd.go
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          npm install
        working-directory: ui
      - name: Lint
        run: |
          npm run lint
        working-directory: ui